config/routes.rb
Rails.application.routes.draw do
  get "page/show"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Defines the root path route ("/")
  root "home#index"

  get "home/index"
  get "page/:slug", to: "pages#show", slug: /[-a-z0-9+]*/, as: :page
  get "/search", to: "search#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/page.rb
class Page < ApplicationRecord
  before_validation :generate_slug

  belongs_to :user
  validates :title, presence: true, uniqueness: true
  validates :content, presence: true
  validates :slug, uniqueness: true, presence: true

  scope :published, -> { where(published: true) }
  scope :ordered, -> { order(created_at: :desc) }
  scope :by_term, ->(term) do
    term.gsub!(/[^-\w] /, "")
    terms = term.split(" ")
    where(terms.map { |t| "content ILIKE ?" }.join(" AND "), *terms.map { |t| "%#{t}%" })
  end

  private

  def generate_slug
    if title.present? && slug.blank?
      slug = title.underscore.parameterize(separator: "_").tr("_", "-")
      (Page.where.not(id: id).where(slug: slug).count > 0) ? slug += "-#{SecureRandom.hex(1)}" : slug
      self.slug = slug
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, :email, presence: true, uniqueness: true
  validates :email, format: {with: URI::MailTo::EMAIL_REGEXP}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @pages = Page.published.ordered
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def show
    @page = Page.published.find_by(slug: params[:slug])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    @page = Page.published.find_by(slug: params[:slug])
  end
end

app/controllers/search_controller.rb
# frozen_string_literal: true

class SearchController < ApplicationController
  def index
    @pages = PageSearch.search(params)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/home/index.html.erb
<%= render "shared/pages", pages: @pages %>

app/views/layouts/_header.html.erb
<header>
  <%= link_to 'My Blog', root_path %>
</header>

app/views/layouts/_search_form.html.erb
<div>
  <%= form_for(:search, url: search_path, method: :get, data: {turbo: false}) do %>
    <%= search_field_tag :term, params[:term] %>
    <%= submit_tag "Search", name: nil %>
  <% end %>
</div>

app/views/layouts/_side_bar.html.erb
<%= render "layouts/search_form" %>
<%= render "layouts/archives" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TddBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <div class="container-fluid">
      <%= render "layouts/header" %>
    </div>
    <main class="container-fluid">
      <div class="row">
        <div class="col-md-9">
          <%= yield %>
        </div>
        <div class="col-md-3">
          <%= render "layouts/side_bar" %>
        </div>
      </div>
    </main>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/pages/show.html.erb
<%= render "shared/page", { page: @page, content: @page.content } %>

app/views/search/index.html.erb
<% if @pages.any? %>
  <%= render "shared/pages", pages: @pages %>
<% else %>
  <p>No results found</p>
<% end %>

app/views/shared/_page.html.erb
<article>
  <header>
    <h2><%= page.title %></h2>
  </header>
  <section>
    <%= content.html_safe %>
  </section>
  <footer>
    <p>Published on
      <%= page.created_at.to_fs %></p>
  </footer>
</article>

app/views/shared/_pages.html.erb
<% pages.each do |page| %>
  <%= render "shared/page", page: page, content: page.summary %>
<% end %>